<?php

namespace Container9edtVb6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NDjlmhKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NDjlmhK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NDjlmhK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeChantierRepository' => ['privates', 'App\\Repository\\TypeChantierRepository', 'getTypeChantierRepositoryService', true],
        ], [
            'typeChantierRepository' => 'App\\Repository\\TypeChantierRepository',
        ]);
    }
}
