<?php

namespace Container9edtVb6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeDevisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._DVoNCC.App\Entity\DemandeDevis' shared service.
     *
     * @return \App\Entity\DemandeDevis
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._DVoNCC": it references class "App\\Entity\\DemandeDevis" but no such service exists.');
    }
}
