<?php

namespace ContainerDcOyxF0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KDH6mTwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KDH6mTw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KDH6mTw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chantier' => ['privates', '.errored..service_locator.KDH6mTw.App\\Entity\\Chantier', NULL, 'Cannot autowire service ".service_locator.KDH6mTw": it references class "App\\Entity\\Chantier" but no such service exists.'],
        ], [
            'chantier' => 'App\\Entity\\Chantier',
        ]);
    }
}
