<?php

namespace ContainerDcOyxF0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeChantierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..5zsod1.App\Entity\TypeChantier' shared service.
     *
     * @return \App\Entity\TypeChantier
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..5zsod1": it references class "App\\Entity\\TypeChantier" but no such service exists.');
    }
}
