vich_uploader:
  db_driver: orm

  mappings:
    chantier_images:
      uri_prefix: "%app.path.chantier_images%"
      upload_destination: "%kernel.project_dir%/public%app.path.chantier_images%"

    reponse_cv:
      uri_prefix: "%app.path.reponse_cv%"
      upload_destination: "%kernel.project_dir%/public%app.path.reponse_cv%"

  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
