<?php

namespace ContainerSzxCNjH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DVoNCCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._DVoNCC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._DVoNCC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demandeDevi' => ['privates', '.errored..service_locator._DVoNCC.App\\Entity\\DemandeDevis', NULL, 'Cannot autowire service ".service_locator._DVoNCC": it references class "App\\Entity\\DemandeDevis" but no such service exists.'],
        ], [
            'demandeDevi' => 'App\\Entity\\DemandeDevis',
        ]);
    }
}
