<?php

namespace Container2OXpDo3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChantierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KDH6mTw.App\Entity\Chantier' shared service.
     *
     * @return \App\Entity\Chantier
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.KDH6mTw": it references class "App\\Entity\\Chantier" but no such service exists.');
    }
}
