<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQxloNl3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQxloNl3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQxloNl3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQxloNl3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQxloNl3\App_KernelDevDebugContainer([
    'container.build_hash' => 'QxloNl3',
    'container.build_id' => 'a275267a',
    'container.build_time' => 1635441970,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQxloNl3');
