<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWENyzZd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWENyzZd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWENyzZd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWENyzZd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWENyzZd\App_KernelDevDebugContainer([
    'container.build_hash' => 'WENyzZd',
    'container.build_id' => '088bd1e5',
    'container.build_time' => 1637243464,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWENyzZd');
