<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIk9UQga\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIk9UQga/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIk9UQga.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIk9UQga\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIk9UQga\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ik9UQga',
    'container.build_id' => '29c60504',
    'container.build_time' => 1635499657,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIk9UQga');
