<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.73ad9136.js',
                '/build/850.5586aae2.js',
                '/build/app.d32657be.js',
            ],
            'css' => [
                '/build/app.b75294ae.css',
            ],
        ],
    ],
],

]];
