const {start} = require('./symfony')
const execute = require('./cmd')
const {execSync} = require('child_process')
const {postgres} = require("../package.json")
const logger = require('./logger')
logger.info('Starting PostGres Server')
cmd = (`postgres -D "${postgres}"`)
logger.warn(cmd)
logger.info('Make Migration')
execute("php bin/console make:migration")
logger.info('Make Migrate Database')
execute("php bin/console doctrine:migrations:migrate")
logger.info('Run NPM libs')
execute("npm run dev")
logger.info('Starting Symfony Server')
start(true)
//execute("npm run watch")