const {start} = require('./symfony')
const execute = require('./cmd')
const {postgres} = require("../package.json")
//str = execute(`postgres -D "${postgres}"`)
//console.log(str)
//execute("php bin/console make:migration")
//execute("php bin/console doctrine:migrations:migrate")
//execute("npm run dev")
start(true)
//execute("npm run watch")